#
# New Relic Infrastructure DirWatcher Integration
#
integration_name: com.newrelic.dirwatcher
instances:
  - name: dirwatcher-metrics-inventory
    command: both
    arguments:
      dir_name: /tmp
      do_recurse: true