name: com.newrelic.dirwatcher
description: DirWatcher
protocol_version: 1
os: linux
commands:
  inventory:
    command:
      - ./newrelic-infra-dirwatcher/dirwatcher
      - --inventory
    prefix: config/dirwatcher
    interval: 60
  metrics:
    command:
      - ./newrelic-infra-dirwatcher/dirwatcher
      - --metrics
    event_name: DirWatcher
    interval: 60
  both:
    command:
      - ./newrelic-infra-dirwatcher/dirwatcher
      - --all
    prefix: config/dirwatcher
    event_name: DirWatcher
    interval: 60
