#
# New Relic Infrastructure DirWatcher Integration
#
name: com.newrelic.dirwatcher
description: DirWatcher
protocol_version: 1
os: windows
commands:
  inventory:
    command:
      - .\newrelic-infra-dirwatcher\dirwatcher.exe
      - --inventory
    prefix: config/dirwatcher
    interval: 60
  metrics:
    command:
      - .\newrelic-infra-dirwatcher\dirwatcher.exe
      - --metrics
    event_name: DirWatcher
    interval: 60
  both:
    command:
      - .\newrelic-infra-dirwatcher\dirwatcher.exe
      - --all
    prefix: config/dirwatcher
    event_name: DirWatcher
    interval: 60
